/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Token;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-06-29T11:48:32.556Z")

@Validated
@Api(value = "oauth2", description = "the oauth2 API")
@RequestMapping(value = "/v1")
public interface Oauth2Api {

    @ApiOperation(value = "Request Access Token", nickname = "oauth2TokenPost", notes = "", response = Token.class, authorizations = {
        @Authorization(value = "Basic")
    }, tags={ "Oauth2", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Authorisation token (Bearer)", response = Token.class),
        @ApiResponse(code = 403, message = "Authentication failed") })
    @RequestMapping(value = "/oauth2/token",
        produces = { "application/json" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Token> oauth2TokenPost(@ApiParam(value = "Value MUST be set to \"client_credentials\" as per RFC", required=true, allowableValues="client_credentials") @RequestParam(value="grant_type", required=true)  String grantType);

}
