/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AccountNumberDetailsResponse;
import io.swagger.model.ApiError;
import io.swagger.model.SortCodeDetailsResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-06-29T11:48:32.556Z")

@Validated
@Api(value = "validations", description = "the validations API")
@RequestMapping(value = "/v1")
public interface ValidationsApi {

    @ApiOperation(value = "Validate sortcode and account number details", nickname = "validationsGbsdcSortcodesSortcodeAccountnumbersAccountnumberGet", notes = "", response = AccountNumberDetailsResponse.class, authorizations = {
        @Authorization(value = "OAuth2", scopes = {
            
            })
    }, tags={ "AccountValidation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sort code and account number details", response = AccountNumberDetailsResponse.class),
        @ApiResponse(code = 400, message = "Validation error", response = ApiError.class),
        @ApiResponse(code = 404, message = "Validation failed", response = ApiError.class) })
    @RequestMapping(value = "/validations/gbsdc/sortcodes/{sortcode}/accountnumbers/{accountnumber}",
        produces = { "application/vnd.api+json", "application/json" }, 
        consumes = { "application/vnd.api+json", "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<AccountNumberDetailsResponse> validationsGbsdcSortcodesSortcodeAccountnumbersAccountnumberGet(@ApiParam(value = "Sort code",required=true) @PathVariable("sortcode") String sortcode,@ApiParam(value = "Account number",required=true) @PathVariable("accountnumber") String accountnumber);


    @ApiOperation(value = "Fetch sort code details", nickname = "validationsGbsdcSortcodesSortcodeGet", notes = "", response = SortCodeDetailsResponse.class, authorizations = {
        @Authorization(value = "OAuth2", scopes = {
            
            })
    }, tags={ "AccountValidation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sort code details", response = SortCodeDetailsResponse.class),
        @ApiResponse(code = 400, message = "Validation failed", response = ApiError.class) })
    @RequestMapping(value = "/validations/gbsdc/sortcodes/{sortcode}",
        produces = { "application/vnd.api+json", "application/json" }, 
        consumes = { "application/vnd.api+json", "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<SortCodeDetailsResponse> validationsGbsdcSortcodesSortcodeGet(@ApiParam(value = "Sort code",required=true) @PathVariable("sortcode") String sortcode);

}
